"""Helpers for exporting reusable figures and tables.

Experiment scripts write run-specific artifacts under timestamped directories in
``results/``. This module additionally supports exporting named figures to
``results/figures/`` and named tables to ``results/tables/`` for convenient
cross-run summaries.
"""

from __future__ import annotations

import contextlib
import datetime as _dt
import io
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

CODE_DIR = Path(__file__).resolve().parents[1]
DEFAULT_FIGURE_DIR = CODE_DIR / "results" / "figures"
DEFAULT_TABLE_DIR = CODE_DIR / "results" / "tables"


def artifact_figures_dir(*, base: Path | None = None) -> Path:
    base = base or DEFAULT_FIGURE_DIR
    base.mkdir(parents=True, exist_ok=True)
    return base


def artifact_tables_dir(*, base: Path | None = None) -> Path:
    base = base or DEFAULT_TABLE_DIR
    base.mkdir(parents=True, exist_ok=True)
    return base


def export_figure(
    fig: plt.Figure,
    name: str,
    *,
    base: Path | None = None,
    formats: tuple[str, ...] = ("pdf",),
    close: bool = True,
    strip_title: bool = True,
    tight_bbox: bool = True,
    dpi: int | None = None,
) -> list[Path]:
    """Save ``fig`` under ``results/figures/<name>.<ext>``."""
    base = artifact_figures_dir(base=base)
    if strip_title:
        for ax in fig.axes:
            ax.set_title("")
    paths: list[Path] = []
    for ext in formats:
        out = base / f"{name}.{ext}"
        if tight_bbox and dpi is not None:
            fig.savefig(out, bbox_inches="tight", dpi=dpi)
        elif tight_bbox:
            fig.savefig(out, bbox_inches="tight")
        elif dpi is not None:
            fig.savefig(out, dpi=dpi)
        else:
            fig.savefig(out)
        paths.append(out)
    if close:
        with contextlib.suppress(Exception):
            plt.close(fig)
    return paths


def export_table(
    df: pd.DataFrame,
    name: str,
    *,
    base: Path | None = None,
    caption: str | None = None,
    floatfmt: str = ".4g",
) -> dict[str, Path]:
    """Save ``df`` under ``results/tables/<name>.{csv,md}``."""
    base = artifact_tables_dir(base=base)
    csv_path = base / f"{name}.csv"
    md_path = base / f"{name}.md"
    df.to_csv(csv_path, index=False)
    md = io.StringIO()
    if caption:
        md.write(f"**{caption}**\n\n")
    md.write(df.to_markdown(index=False, floatfmt=floatfmt))
    md.write("\n")
    md_path.write_text(md.getvalue(), encoding="utf-8")
    return {"csv": csv_path, "md": md_path}


def write_index(entries: list[dict[str, Any]], *, base: Path | None = None) -> Path:
    """Append a Markdown index of exported figures/tables."""
    base = artifact_figures_dir(base=base)
    path = base / "INDEX.md"
    grouped: dict[str, list[dict[str, Any]]] = {"plot": [], "summary table": []}
    for entry in entries:
        grouped.setdefault(entry["kind"], []).append(entry)
    out = io.StringIO()
    out.write("# Exported figures and tables\n\n")
    out.write(
        "_Auto-generated by `src.artifact_export`; "
        f"last update {_dt.datetime.now().isoformat(timespec='seconds')}_.\n\n"
    )
    for kind, items in grouped.items():
        if not items:
            continue
        out.write(f"## {kind.capitalize()}s\n\n")
        for it in items:
            cap = it.get("caption", "")
            out.write(f"- `{Path(it['path']).name}`: {cap}\n")
        out.write("\n")
    path.write_text(out.getvalue(), encoding="utf-8")
    return path


def classify_paths_by_limit(
    final_prices: np.ndarray,
    *,
    p_NE: np.ndarray,
    p_C: np.ndarray,
) -> dict[str, np.ndarray]:
    """Classify each seed by which benchmark its long-run prices are closest to."""
    _, _S = final_prices.shape
    p_NE_avg = float(np.mean(p_NE))
    p_C_avg = float(np.mean(p_C))
    span = abs(p_C_avg - p_NE_avg)
    if span < 1e-12:
        raise ValueError("p_NE == p_C; cannot classify")
    near_thresh = 0.10 * span
    avg_seed_price = final_prices.mean(axis=0)
    d_NE = np.abs(avg_seed_price - p_NE_avg)
    d_C = np.abs(avg_seed_price - p_C_avg)
    is_NE = d_NE < near_thresh
    is_C = d_C < near_thresh
    is_inter = (~is_NE) & (~is_C)
    return {
        "near_NE": np.where(is_NE)[0],
        "near_C": np.where(is_C)[0],
        "indeterminate": np.where(is_inter)[0],
    }


def pick_representative_seeds(
    final_prices: np.ndarray,
    *,
    p_NE: np.ndarray,
    p_C: np.ndarray,
) -> dict[str, int | None]:
    """Pick one representative seed per regime."""
    p_NE_avg = float(np.mean(p_NE))
    p_C_avg = float(np.mean(p_C))
    mid = 0.5 * (p_NE_avg + p_C_avg)
    if final_prices.size == 0:
        return {"near_NE": None, "near_C": None, "indeterminate": None}
    avg = final_prices.mean(axis=0)
    chosen: dict[str, int | None] = {
        "near_NE": int(np.argmin(np.abs(avg - p_NE_avg))),
        "near_C": int(np.argmax(avg)),
        "indeterminate": int(np.argmin(np.abs(avg - mid))),
    }
    seen: set[int] = set()
    for label in ("near_NE", "near_C", "indeterminate"):
        candidate = chosen[label]
        if candidate is None:
            continue
        if candidate in seen:
            ranking = np.argsort(
                np.abs(avg - (p_NE_avg if label == "near_NE" else p_C_avg if label == "near_C" else mid)),
            )
            for s in ranking:
                s_int = int(s)
                if s_int not in seen:
                    chosen[label] = s_int
                    candidate = s_int
                    break
        seen.add(candidate)
    return chosen

